services:
  - type: web
    name: crops-disease-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --threads 2
    envVars:
      - key: PORT
        value: 10000
